### ISSUE TITLE
Milestone Todo

### ISSUE THREAD

**Issue by AnweshDahal** [AnweshDahal/Wosaa_Fashion_Store#3]
### Here are our milestone 1 goals

- [x] Build GUI
- [x] Add Insertion Functionality
- [x] Add Validation Feature
- [x] Add Price Search Functionality
- [x] Add Type Search Functionality
- [x] Big Fix Session 1
- [x] Add import from CSV functionality
